{
  "rules": [
    {"opcode": 0x00, "mnemonic": "ADD", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x01, "mnemonic": "ADD", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x02, "mnemonic": "ADD", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x03, "mnemonic": "ADD", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x04, "mnemonic": "ADD", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x05, "mnemonic": "ADD", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x06, "mnemonic": "PUSH ES", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x07, "mnemonic": "POP ES", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x08, "mnemonic": "OR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x09, "mnemonic": "OR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x0A, "mnemonic": "OR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x0B, "mnemonic": "OR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x0C, "mnemonic": "OR", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x0D, "mnemonic": "OR", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x0E, "mnemonic": "PUSH CS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x0F, "mnemonic": "POP CS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x10, "mnemonic": "ADC", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x11, "mnemonic": "ADC", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x12, "mnemonic": "ADC", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x13, "mnemonic": "ADC", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x14, "mnemonic": "ADC", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x15, "mnemonic": "ADC", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x16, "mnemonic": "PUSH SS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x17, "mnemonic": "POP SS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x18, "mnemonic": "SBB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x19, "mnemonic": "SBB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x1A, "mnemonic": "SBB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x1B, "mnemonic": "SBB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x1C, "mnemonic": "SBB", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x1D, "mnemonic": "SBB", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x1E, "mnemonic": "PUSH DS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x1F, "mnemonic": "POP DS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x20, "mnemonic": "AND", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x21, "mnemonic": "AND", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x22, "mnemonic": "AND", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x23, "mnemonic": "AND", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x24, "mnemonic": "AND", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x25, "mnemonic": "AND", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x26, "mnemonic": "ES", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x27, "mnemonic": "DAS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x28, "mnemonic": "SUB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x29, "mnemonic": "SUB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x2A, "mnemonic": "SUB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x2B, "mnemonic": "SUB", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x2C, "mnemonic": "SUB", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x2D, "mnemonic": "SUB", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x2E, "mnemonic": "CS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x2F, "mnemonic": "SUB", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x30, "mnemonic": "XOR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x31, "mnemonic": "XOR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x32, "mnemonic": "XOR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x33, "mnemonic": "XOR", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x34, "mnemonic": "XOR", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x35, "mnemonic": "XOR", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x36, "mnemonic": "SS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x37, "mnemonic": "AAA", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x38, "mnemonic": "CMP", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x39, "mnemonic": "CMP", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x3A, "mnemonic": "CMP", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x3B, "mnemonic": "CMP", "usesModRM": true, "operandFormat": "register_register"},
    {"opcode": 0x3C, "mnemonic": "CMP", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x3D, "mnemonic": "CMP", "usesModRM": false, "operandFormat": "immediate_register"},
    {"opcode": 0x3E, "mnemonic": "DS", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x3F, "mnemonic": "CMP", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x40, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x41, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x42, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x43, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x44, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x45, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x46, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x47, "mnemonic": "INC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x48, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x49, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4A, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4B, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4C, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4D, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4E, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x4F, "mnemonic": "DEC", "usesModRM": true, "operandFormat": "register"},
    {"opcode": 0x50, "mnemonic": "PUSH AX", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x51, "mnemonic": "PUSH CX", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x52, "mnemonic": "PUSH DX", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x53, "mnemonic": "PUSH BX", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x54, "mnemonic": "PUSH SP", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x55, "mnemonic": "PUSH BP", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x56, "mnemonic": "PUSH SI", "usesModRM": false, "operandFormat": "none"},
    {"opcode": 0x57, "mnemonic": "PUSH DI", "usesModRM": false, "operandFormat": "none"}
  ]
}
